# Generated by Django 4.1.5 on 2023-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("productId", models.AutoField(primary_key=True, serialize=False)),
                ("productName", models.CharField(max_length=230)),
                ("productOwnerName", models.CharField(max_length=230)),
                ("Developers", models.JSONField(default=list)),
                ("scrumMasterName", models.CharField(max_length=230)),
                ("startDate", models.DateField()),
                ("methodology", models.CharField(max_length=230)),
            ],
        ),
    ]
